# print("---Generator Nama Usaha---")
# print("Selamat datang di generator nama usaha\nSelamat mencoba:v")
# a = (input("Masukkan tempat tinggal anda: "))
# b = (input("Masukkan nama hewan peliharaan anda: "))
# hasil = ("Nama usaha anda adalah: ")
# print(hasil+"\n"+a+" "+b)

print("---Generator Nama Usaha---")
print("Selamat datang di generator nama usaha\nSelamat mencoba:v")
print("Masukkan tempat tinggal anda:")
a = input()
print("Masukkan nama hewan peliharaan anda:")
b = input()
print("Nama usaha anda adalah:")
print(a+" "+b)
